version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_HOST:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_HOST:-guest}