version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_HOST:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_HOST:-guest}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  extractor:
    build:
      context: .
      args:
        - MVN_PROFILE=cmsint-pac-extractor
    ports:
      - "8080:8080"
    environment:
     - PAC_QUEUE_NAME=${PAC_QUEUE_NAME:-pac-queue}
     - PAC_ROUTING_KEY=${PAC_ROUTING_KEY:-PAC}
     - RABBIT_EXCHANGE_NAME=${RABBIT_EXCHANGE_NAME:-EXCHANGE}
     - ORDS_USERNAME=${ORDS_USERNAME:-''}
     - ORDS_PASSWORD=${ORDS_PASSWORD:-''}
     - ORDS_HOST=${ORDS_HOST:-127.0.0.1/}
     - RABBIT_MQ_HOST=${RABBIT_MQ_HOST:-rabbitmq}
     - RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME:-guest}
     - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD-guest}
     - EXTRACTOR_SERVER_PORT=${EXTRACTOR_SERVER_PORT:-8080}
     - EXTRACTOR_MANAGEMENT_SERVER_PORT=${EXTRACTOR_MANAGEMENT_SERVER_PORT:-8081}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 10s
    depends_on:
      - rabbitmq