pac:
  pacQueue: ${PAC_QUEUE_NAME:pac-queue}
  pacRoutingKey: ${PAC_ROUTING_KEY:PAC}
  exchangeName: ${RABBIT_EXCHANGE_NAME:EXCHANGE}
  serviceUrl: ${PAC_SERVICE_URL:https://127.0.0.1/}
  cmsDatePattern: ${CMS_DATE_PATTERN:yyyy-MM-dd}
  pacDatePattern: ${PAC_DATE_PATTERN:yyyy-MM-dd}
  icsDatePattern: ${ICS_DATE_PATTERN:yyyyMMdd}

ords:
  host: ${ORDS_HOST:https://127.0.0.1/}
  successEndpoint: "success"

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:127.0.0.1}
    port: 5672
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

server:
  port: ${CONSUMER_SERVER_PORT:8082}

management:
  server:
    port: ${CONSUMER_MANAGEMENT_SERVER_PORT:8083}
