apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${COMPONENT_NAME}
  description: Deployment template for the cmsint-pac-extractor

labels:
  app: ${APP_NAME}
  app.kubernetes.io/name: ${COMPONENT_NAME}
  app.kubernetes.io/part-of: ${APP_NAME}
  app.openshift.io/runtime: ${RUNTIME}

parameters:

  - name: APP_NAME
    description: The application name that each component is part of
    required: false
    value: jag-cmsint-pac

  - name: COMPONENT_NAME
    description: The component name
    required: false
    value: cmsint-pac-extractor

  - name: OC_NAMESPACE
    description: The OpenShift namespace prefix
    required: false
    # Below value must be changed as per gold cluster oc nameplate
    value: e1a6d6

  - name: OC_ENV
    description: The OpenShift environment, ie dev, test or prod
    required: true

  - name: RUNTIME
    description: The application run time language
    required: false
    value: java

objects:

  ### cmsint-pac-extractor deployment config ###
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${COMPONENT_NAME}
      namespace: ${OC_NAMESPACE}-${OC_ENV}
    spec:
      completionDeadlineSeconds: 1200
      replicas: 2
      selector:
        name: ${COMPONENT_NAME}
      strategy:
        type: Rolling
        maxSurge: 50%
        maxUnavailable: 0
      template:
        metadata:
          labels:
            name: ${COMPONENT_NAME}
        spec:
          containers:
            # Below Image url must be changed as per gold cluster image stream
            - image: >-
                image-registry.openshift-image-registry.svc:5000/${OC_NAMESPACE}-tools/${COMPONENT_NAME}:${OC_ENV}
              name: ${COMPONENT_NAME}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
              env:
                - name: EXTRACTOR_MANAGEMENT_SERVER_PORT
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: EXTRACTOR_MANAGEMENT_SERVER_PORT
                - name: EXTRACTOR_SERVER_PORT
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: EXTRACTOR_SERVER_PORT
                - name: CMSINT_ORDS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: CMSINT_ORDS_HOST
                - name: CMS_ORDS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: CMS_ORDS_HOST
                - name: CMSINT_ORDS_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: CMSINT_ORDS_USERNAME
                - name: CMSINT_ORDS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: CMSINT_ORDS_PASSWORD
                - name: CMS_ORDS_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: CMS_ORDS_USERNAME
                - name: CMS_ORDS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: CMS_ORDS_PASSWORD
                - name: PAC_QUEUE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: PAC_QUEUE_NAME
                - name: PAC_ROUTING_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: PAC_ROUTING_KEY
                - name: RABBIT_EXCHANGE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: RABBIT_EXCHANGE_NAME
                - name: SPRING_PROFILES_ACTIVE
                  valueFrom:
                    secretKeyRef:
                      name: ${COMPONENT_NAME}
                      key: SPRING_PROFILE
                - name: RABBIT_MQ_HOST
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-cluster-secret
                      key: host
                - name: RABBIT_MQ_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-cluster-secret
                      key: username
                - name: RABBIT_MQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-cluster-secret
                      key: password
                - name: SPLUNK_HTTP_URL
                  valueFrom:
                    secretKeyRef:
                      name: cmsint-pac-splunk-config
                      key: SPLUNK_HTTP_URL
                - name: SPLUNK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cmsint-pac-splunk-config
                      key: SPLUNK_TOKEN
                - name: SPLUNK_INDEX
                  valueFrom:
                    secretKeyRef:
                      name: cmsint-pac-splunk-config
                      key: SPLUNK_INDEX
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${COMPONENT_NAME}
            from:
              kind: ImageStreamTag
              namespace: ${OC_NAMESPACE}-tools
              name: ${COMPONENT_NAME}:${OC_ENV}


  ### cmsint-pac-extractor service ###
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${COMPONENT_NAME}
      namespace: ${OC_NAMESPACE}-${OC_ENV}
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        name: ${COMPONENT_NAME}
      sessionAffinity: None
      type: ClusterIP
